/**
 * This class is generated by jOOQ
 */
package io.cattle.platform.core.model.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class HostDiskTable extends org.jooq.impl.TableImpl<io.cattle.platform.core.model.tables.records.HostDiskRecord> {

	private static final long serialVersionUID = -231385098;

	/**
	 * The singleton instance of <code>cattle.host_disk</code>
	 */
	public static final io.cattle.platform.core.model.tables.HostDiskTable HOST_DISK = new io.cattle.platform.core.model.tables.HostDiskTable();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<io.cattle.platform.core.model.tables.records.HostDiskRecord> getRecordType() {
		return io.cattle.platform.core.model.tables.records.HostDiskRecord.class;
	}

	/**
	 * The column <code>cattle.host_disk.id</code>.
	 */
	public final org.jooq.TableField<io.cattle.platform.core.model.tables.records.HostDiskRecord, java.lang.Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>cattle.host_disk.name</code>.
	 */
	public final org.jooq.TableField<io.cattle.platform.core.model.tables.records.HostDiskRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>cattle.host_disk.account_id</code>.
	 */
	public final org.jooq.TableField<io.cattle.platform.core.model.tables.records.HostDiskRecord, java.lang.Long> ACCOUNT_ID = createField("account_id", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>cattle.host_disk.kind</code>.
	 */
	public final org.jooq.TableField<io.cattle.platform.core.model.tables.records.HostDiskRecord, java.lang.String> KIND = createField("kind", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>cattle.host_disk.uuid</code>.
	 */
	public final org.jooq.TableField<io.cattle.platform.core.model.tables.records.HostDiskRecord, java.lang.String> UUID = createField("uuid", org.jooq.impl.SQLDataType.VARCHAR.length(128).nullable(false), this, "");

	/**
	 * The column <code>cattle.host_disk.description</code>.
	 */
	public final org.jooq.TableField<io.cattle.platform.core.model.tables.records.HostDiskRecord, java.lang.String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.VARCHAR.length(1024), this, "");

	/**
	 * The column <code>cattle.host_disk.state</code>.
	 */
	public final org.jooq.TableField<io.cattle.platform.core.model.tables.records.HostDiskRecord, java.lang.String> STATE = createField("state", org.jooq.impl.SQLDataType.VARCHAR.length(128).nullable(false), this, "");

	/**
	 * The column <code>cattle.host_disk.created</code>.
	 */
	public final org.jooq.TableField<io.cattle.platform.core.model.tables.records.HostDiskRecord, java.util.Date> CREATED = createField("created", org.jooq.impl.SQLDataType.TIMESTAMP.asConvertedDataType(new io.cattle.platform.db.jooq.converter.DateConverter()), this, "");

	/**
	 * The column <code>cattle.host_disk.removed</code>.
	 */
	public final org.jooq.TableField<io.cattle.platform.core.model.tables.records.HostDiskRecord, java.util.Date> REMOVED = createField("removed", org.jooq.impl.SQLDataType.TIMESTAMP.asConvertedDataType(new io.cattle.platform.db.jooq.converter.DateConverter()), this, "");

	/**
	 * The column <code>cattle.host_disk.remove_time</code>.
	 */
	public final org.jooq.TableField<io.cattle.platform.core.model.tables.records.HostDiskRecord, java.util.Date> REMOVE_TIME = createField("remove_time", org.jooq.impl.SQLDataType.TIMESTAMP.asConvertedDataType(new io.cattle.platform.db.jooq.converter.DateConverter()), this, "");

	/**
	 * The column <code>cattle.host_disk.data</code>.
	 */
	public final org.jooq.TableField<io.cattle.platform.core.model.tables.records.HostDiskRecord, java.util.Map<String,Object>> DATA = createField("data", org.jooq.impl.SQLDataType.CLOB.length(65535).asConvertedDataType(new io.cattle.platform.db.jooq.converter.DataConverter()), this, "");

	/**
	 * The column <code>cattle.host_disk.total_size</code>.
	 */
	public final org.jooq.TableField<io.cattle.platform.core.model.tables.records.HostDiskRecord, java.lang.Long> TOTAL_SIZE = createField("total_size", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>cattle.host_disk.allocated_size</code>.
	 */
	public final org.jooq.TableField<io.cattle.platform.core.model.tables.records.HostDiskRecord, java.lang.Long> ALLOCATED_SIZE = createField("allocated_size", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>cattle.host_disk.host_id</code>.
	 */
	public final org.jooq.TableField<io.cattle.platform.core.model.tables.records.HostDiskRecord, java.lang.Long> HOST_ID = createField("host_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * Create a <code>cattle.host_disk</code> table reference
	 */
	public HostDiskTable() {
		this("host_disk", null);
	}

	/**
	 * Create an aliased <code>cattle.host_disk</code> table reference
	 */
	public HostDiskTable(java.lang.String alias) {
		this(alias, io.cattle.platform.core.model.tables.HostDiskTable.HOST_DISK);
	}

	private HostDiskTable(java.lang.String alias, org.jooq.Table<io.cattle.platform.core.model.tables.records.HostDiskRecord> aliased) {
		this(alias, aliased, null);
	}

	private HostDiskTable(java.lang.String alias, org.jooq.Table<io.cattle.platform.core.model.tables.records.HostDiskRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, io.cattle.platform.core.model.CattleTable.CATTLE, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<io.cattle.platform.core.model.tables.records.HostDiskRecord, java.lang.Long> getIdentity() {
		return io.cattle.platform.core.model.Keys.IDENTITY_HOST_DISK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<io.cattle.platform.core.model.tables.records.HostDiskRecord> getPrimaryKey() {
		return io.cattle.platform.core.model.Keys.KEY_HOST_DISK_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<io.cattle.platform.core.model.tables.records.HostDiskRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<io.cattle.platform.core.model.tables.records.HostDiskRecord>>asList(io.cattle.platform.core.model.Keys.KEY_HOST_DISK_PRIMARY, io.cattle.platform.core.model.Keys.KEY_HOST_DISK_IDX_HOST_DISK_UUID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<io.cattle.platform.core.model.tables.records.HostDiskRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<io.cattle.platform.core.model.tables.records.HostDiskRecord, ?>>asList(io.cattle.platform.core.model.Keys.FK_HOST_DISK__ACCOUNT_ID, io.cattle.platform.core.model.Keys.FK_HOST_DISK__HOST_ID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public io.cattle.platform.core.model.tables.HostDiskTable as(java.lang.String alias) {
		return new io.cattle.platform.core.model.tables.HostDiskTable(alias, this);
	}

	/**
	 * Rename this table
	 */
	public io.cattle.platform.core.model.tables.HostDiskTable rename(java.lang.String name) {
		return new io.cattle.platform.core.model.tables.HostDiskTable(name, null);
	}
}
