/**
 * This class is generated by jOOQ
 */
package io.cattle.platform.core.model.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InstanceDiskMapTable extends org.jooq.impl.TableImpl<io.cattle.platform.core.model.tables.records.InstanceDiskMapRecord> {

	private static final long serialVersionUID = 2037364383;

	/**
	 * The singleton instance of <code>cattle.instance_disk_map</code>
	 */
	public static final io.cattle.platform.core.model.tables.InstanceDiskMapTable INSTANCE_DISK_MAP = new io.cattle.platform.core.model.tables.InstanceDiskMapTable();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<io.cattle.platform.core.model.tables.records.InstanceDiskMapRecord> getRecordType() {
		return io.cattle.platform.core.model.tables.records.InstanceDiskMapRecord.class;
	}

	/**
	 * The column <code>cattle.instance_disk_map.id</code>.
	 */
	public final org.jooq.TableField<io.cattle.platform.core.model.tables.records.InstanceDiskMapRecord, java.lang.Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>cattle.instance_disk_map.kind</code>.
	 */
	public final org.jooq.TableField<io.cattle.platform.core.model.tables.records.InstanceDiskMapRecord, java.lang.String> KIND = createField("kind", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>cattle.instance_disk_map.uuid</code>.
	 */
	public final org.jooq.TableField<io.cattle.platform.core.model.tables.records.InstanceDiskMapRecord, java.lang.String> UUID = createField("uuid", org.jooq.impl.SQLDataType.VARCHAR.length(128).nullable(false), this, "");

	/**
	 * The column <code>cattle.instance_disk_map.description</code>.
	 */
	public final org.jooq.TableField<io.cattle.platform.core.model.tables.records.InstanceDiskMapRecord, java.lang.String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.VARCHAR.length(1024), this, "");

	/**
	 * The column <code>cattle.instance_disk_map.state</code>.
	 */
	public final org.jooq.TableField<io.cattle.platform.core.model.tables.records.InstanceDiskMapRecord, java.lang.String> STATE = createField("state", org.jooq.impl.SQLDataType.VARCHAR.length(128).nullable(false), this, "");

	/**
	 * The column <code>cattle.instance_disk_map.created</code>.
	 */
	public final org.jooq.TableField<io.cattle.platform.core.model.tables.records.InstanceDiskMapRecord, java.util.Date> CREATED = createField("created", org.jooq.impl.SQLDataType.TIMESTAMP.asConvertedDataType(new io.cattle.platform.db.jooq.converter.DateConverter()), this, "");

	/**
	 * The column <code>cattle.instance_disk_map.removed</code>.
	 */
	public final org.jooq.TableField<io.cattle.platform.core.model.tables.records.InstanceDiskMapRecord, java.util.Date> REMOVED = createField("removed", org.jooq.impl.SQLDataType.TIMESTAMP.asConvertedDataType(new io.cattle.platform.db.jooq.converter.DateConverter()), this, "");

	/**
	 * The column <code>cattle.instance_disk_map.remove_time</code>.
	 */
	public final org.jooq.TableField<io.cattle.platform.core.model.tables.records.InstanceDiskMapRecord, java.util.Date> REMOVE_TIME = createField("remove_time", org.jooq.impl.SQLDataType.TIMESTAMP.asConvertedDataType(new io.cattle.platform.db.jooq.converter.DateConverter()), this, "");

	/**
	 * The column <code>cattle.instance_disk_map.data</code>.
	 */
	public final org.jooq.TableField<io.cattle.platform.core.model.tables.records.InstanceDiskMapRecord, java.util.Map<String,Object>> DATA = createField("data", org.jooq.impl.SQLDataType.CLOB.length(65535).asConvertedDataType(new io.cattle.platform.db.jooq.converter.DataConverter()), this, "");

	/**
	 * The column <code>cattle.instance_disk_map.instance_id</code>.
	 */
	public final org.jooq.TableField<io.cattle.platform.core.model.tables.records.InstanceDiskMapRecord, java.lang.Long> INSTANCE_ID = createField("instance_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>cattle.instance_disk_map.disk_id</code>.
	 */
	public final org.jooq.TableField<io.cattle.platform.core.model.tables.records.InstanceDiskMapRecord, java.lang.Long> DISK_ID = createField("disk_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>cattle.instance_disk_map.reserve_size</code>.
	 */
	public final org.jooq.TableField<io.cattle.platform.core.model.tables.records.InstanceDiskMapRecord, java.lang.Long> RESERVE_SIZE = createField("reserve_size", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * Create a <code>cattle.instance_disk_map</code> table reference
	 */
	public InstanceDiskMapTable() {
		this("instance_disk_map", null);
	}

	/**
	 * Create an aliased <code>cattle.instance_disk_map</code> table reference
	 */
	public InstanceDiskMapTable(java.lang.String alias) {
		this(alias, io.cattle.platform.core.model.tables.InstanceDiskMapTable.INSTANCE_DISK_MAP);
	}

	private InstanceDiskMapTable(java.lang.String alias, org.jooq.Table<io.cattle.platform.core.model.tables.records.InstanceDiskMapRecord> aliased) {
		this(alias, aliased, null);
	}

	private InstanceDiskMapTable(java.lang.String alias, org.jooq.Table<io.cattle.platform.core.model.tables.records.InstanceDiskMapRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, io.cattle.platform.core.model.CattleTable.CATTLE, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<io.cattle.platform.core.model.tables.records.InstanceDiskMapRecord, java.lang.Long> getIdentity() {
		return io.cattle.platform.core.model.Keys.IDENTITY_INSTANCE_DISK_MAP;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<io.cattle.platform.core.model.tables.records.InstanceDiskMapRecord> getPrimaryKey() {
		return io.cattle.platform.core.model.Keys.KEY_INSTANCE_DISK_MAP_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<io.cattle.platform.core.model.tables.records.InstanceDiskMapRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<io.cattle.platform.core.model.tables.records.InstanceDiskMapRecord>>asList(io.cattle.platform.core.model.Keys.KEY_INSTANCE_DISK_MAP_PRIMARY, io.cattle.platform.core.model.Keys.KEY_INSTANCE_DISK_MAP_IDX_INSTANCE_DISK_UUID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<io.cattle.platform.core.model.tables.records.InstanceDiskMapRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<io.cattle.platform.core.model.tables.records.InstanceDiskMapRecord, ?>>asList(io.cattle.platform.core.model.Keys.FK_INSTANCE_DISK__INSTANCE_ID, io.cattle.platform.core.model.Keys.FK_INSTANCE_DISK__DISK_ID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public io.cattle.platform.core.model.tables.InstanceDiskMapTable as(java.lang.String alias) {
		return new io.cattle.platform.core.model.tables.InstanceDiskMapTable(alias, this);
	}

	/**
	 * Rename this table
	 */
	public io.cattle.platform.core.model.tables.InstanceDiskMapTable rename(java.lang.String name) {
		return new io.cattle.platform.core.model.tables.InstanceDiskMapTable(name, null);
	}
}
