/**
 * This class is generated by jOOQ
 */
package io.cattle.platform.core.model;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
@javax.persistence.Entity
@javax.persistence.Table(name = "host_disk", schema = "cattle")
public interface HostDisk extends java.io.Serializable {

	/**
	 * Setter for <code>cattle.host_disk.id</code>.
	 */
	public void setId(java.lang.Long value);

	/**
	 * Getter for <code>cattle.host_disk.id</code>.
	 */
	@javax.persistence.Id
	@javax.persistence.Column(name = "id", unique = true, nullable = false, precision = 19)
	public java.lang.Long getId();

	/**
	 * Setter for <code>cattle.host_disk.name</code>.
	 */
	public void setName(java.lang.String value);

	/**
	 * Getter for <code>cattle.host_disk.name</code>.
	 */
	@javax.persistence.Column(name = "name", nullable = false, length = 255)
	public java.lang.String getName();

	/**
	 * Setter for <code>cattle.host_disk.account_id</code>.
	 */
	public void setAccountId(java.lang.Long value);

	/**
	 * Getter for <code>cattle.host_disk.account_id</code>.
	 */
	@javax.persistence.Column(name = "account_id", precision = 19)
	public java.lang.Long getAccountId();

	/**
	 * Setter for <code>cattle.host_disk.kind</code>.
	 */
	public void setKind(java.lang.String value);

	/**
	 * Getter for <code>cattle.host_disk.kind</code>.
	 */
	@javax.persistence.Column(name = "kind", nullable = false, length = 255)
	public java.lang.String getKind();

	/**
	 * Setter for <code>cattle.host_disk.uuid</code>.
	 */
	public void setUuid(java.lang.String value);

	/**
	 * Getter for <code>cattle.host_disk.uuid</code>.
	 */
	@javax.persistence.Column(name = "uuid", unique = true, nullable = false, length = 128)
	public java.lang.String getUuid();

	/**
	 * Setter for <code>cattle.host_disk.description</code>.
	 */
	public void setDescription(java.lang.String value);

	/**
	 * Getter for <code>cattle.host_disk.description</code>.
	 */
	@javax.persistence.Column(name = "description", length = 1024)
	public java.lang.String getDescription();

	/**
	 * Setter for <code>cattle.host_disk.state</code>.
	 */
	public void setState(java.lang.String value);

	/**
	 * Getter for <code>cattle.host_disk.state</code>.
	 */
	@javax.persistence.Column(name = "state", nullable = false, length = 128)
	public java.lang.String getState();

	/**
	 * Setter for <code>cattle.host_disk.created</code>.
	 */
	public void setCreated(java.util.Date value);

	/**
	 * Getter for <code>cattle.host_disk.created</code>.
	 */
	@javax.persistence.Column(name = "created")
	public java.util.Date getCreated();

	/**
	 * Setter for <code>cattle.host_disk.removed</code>.
	 */
	public void setRemoved(java.util.Date value);

	/**
	 * Getter for <code>cattle.host_disk.removed</code>.
	 */
	@javax.persistence.Column(name = "removed")
	public java.util.Date getRemoved();

	/**
	 * Setter for <code>cattle.host_disk.remove_time</code>.
	 */
	public void setRemoveTime(java.util.Date value);

	/**
	 * Getter for <code>cattle.host_disk.remove_time</code>.
	 */
	@javax.persistence.Column(name = "remove_time")
	public java.util.Date getRemoveTime();

	/**
	 * Setter for <code>cattle.host_disk.data</code>.
	 */
	public void setData(java.util.Map<String,Object> value);

	/**
	 * Getter for <code>cattle.host_disk.data</code>.
	 */
	@javax.persistence.Column(name = "data", length = 65535)
	public java.util.Map<String,Object> getData();

	/**
	 * Setter for <code>cattle.host_disk.total_size</code>.
	 */
	public void setTotalSize(java.lang.Long value);

	/**
	 * Getter for <code>cattle.host_disk.total_size</code>.
	 */
	@javax.persistence.Column(name = "total_size", precision = 19)
	public java.lang.Long getTotalSize();

	/**
	 * Setter for <code>cattle.host_disk.allocated_size</code>.
	 */
	public void setAllocatedSize(java.lang.Long value);

	/**
	 * Getter for <code>cattle.host_disk.allocated_size</code>.
	 */
	@javax.persistence.Column(name = "allocated_size", precision = 19)
	public java.lang.Long getAllocatedSize();

	/**
	 * Setter for <code>cattle.host_disk.host_id</code>.
	 */
	public void setHostId(java.lang.Long value);

	/**
	 * Getter for <code>cattle.host_disk.host_id</code>.
	 */
	@javax.persistence.Column(name = "host_id", nullable = false, precision = 19)
	public java.lang.Long getHostId();

	// -------------------------------------------------------------------------
	// FROM and INTO
	// -------------------------------------------------------------------------

	/**
	 * Load data from another generated Record/POJO implementing the common interface HostDisk
	 */
	public void from(io.cattle.platform.core.model.HostDisk from);

	/**
	 * Copy data into another generated Record/POJO implementing the common interface HostDisk
	 */
	public <E extends io.cattle.platform.core.model.HostDisk> E into(E into);
}
